### ISSUE TITLE
Study Tracker Improvements

### ISSUE THREAD

**Issue by taracampbell** [taracampbell/Loris#22]
### General
- [x] Get visit labels without underline :goat:
- [x] Get equal width for each visit column
- [ ] After highlighting a row or column, clicking outside of that row or column should make the highlight go away
- [x] PSCID or CandID - which should be using? PSCID - Zia
- [x] Add info for DDE instruments :goat:
- [ ] Add info for data monitoring (on hold)
- [x] Add legend :goat: (to be put in help)
- [x] Create design for requested features #25
- [x] Integrate into current dashboard

### Candidate Sidebar
- [x] Link to Candidate Profile :goat:
- [ ] Fix spacing & typography :large_blue_diamond:
- [x] Add detailed information about instruments  :goat:

### Visit Sidebar
- [ ] Fix spacing :large_blue_diamond:

### Tooltip
- [ ] Fix spacing

### AJAX issues
- [x] Sometimes the number of completed instruments is greater than the number of instruments for that visit (shown in the tooltip) - @davidblader did you fix this somehow? I'm not seeing the issue anymore.
- [ ] Weird case to fix: for candidates where the Screening Visit hasn't been registered but another one has
- [ ] Clean-up AJAX and make it more efficient, consider fetching data from one site at a time only?

### Permissions
- [x] Some users should only be able to see their own site data
      - will need to do a rebase on 17.1 to incorporate multi-site functionality

### Cool things to add
- [x] Column sorting  (based on deadline)
- [ ] In the candidate instrument focus, add ability to collapse visits, OR
- [x] show candidate instrument focus for particular visit when clicking on visit circle :goat: (Let's do both? -Tara)
- [x] When there are no candidates for a specific filter, write in the table "No candidates" so that users don't wait for something to load

### Clean-up
- [x] prettyStatus method in StudyTracker class does not need to be within class and passed along as a prop, could be external or better yet replaced with a better way of formatting and styling the information :goat:
- [x] Add active class to sidebar nav when clicked on, and get rid of React errors
- [ ] replace all jQuery usage with vanilla JS or react supported equivalents

### Phase 3

- [x] Filtering for Candidate
- [x] A link to the feedback module/conflict resolver for the given instrument/commentID
- [x] Include the Date of participant registration as a sortable column in study tracker
- [x] Include the participant status of the participant (i.e. withdrawal)
- [x] Change circle colour to something other than light grey if participant is withdrawn

**Comment by taracampbell** [comment]
@davidblader feel free to edit, comment, create new issues, etc.

:large_blue_diamond: Means I am working on it

**Comment by davidblader** [comment]
:goat: means i'm working on it

**Comment by mohadesz** [comment]
@taracampbell @davidblader Are these tasks up-to-date? If not , please check the ones that are already completed.

**Comment by davidblader** [comment]
> @davidblader did you fix this somehow? I'm not seeing the issue anymore.

yeah this was because the original instrument completion count was including completion of DDE instruments

**Comment by mohadesz** [comment]
@taracampbell @davidblader  Couple of extra items to be added:

1- Filtering for Visit-labels and Candidate
2- A link to the feedback module/conflict resolver for the given instrument/commentID ( We can add an icon right next to the instrument)

**Comment by taracampbell** [comment]
@mohadesz  what do you mean by filtering by visit labels? Is that something CCNA people asked for? All the visit labels are easily visible at the top, and if you click one, you get a summary of deadlines for the visit. Not sure what filtering by visit label would look like.

**Comment by mohadesz** [comment]
@taracampbell yes forget about the VL search (I was thinking of combining it with Candidate filter) but as you have mentioned this may not be needed
