### ISSUE TITLE
Study Tracker Improvements Phase 3.0

### ISSUE THREAD

**Issue by mohadesz** [taracampbell/Loris#37]
Possible Improvements:

- [x] 1- Filtering for Candidate
- [x] 2- A link to the feedback module for the given instrument/commentID ( We can add an icon right next to the Candidate/Visit)
- [x] 3- A link to the conflict resolver for the given instrument/commentID ( We can add an icon right next to the Candidate/Visit)

Requested by Victor
- [x] 4- Include the Date of participant registration as a sortable column in study tracker (Requested by Victor)(
- [x] 5- Site-based Permission will be fine (i.e. include only the sites that user is part of) - Approved by Victor
- [x] 6- Include the participant status of the participant (i.e. withdrawal) - We can discuss on how this should be displayed on the front-end
		- If a candidate is withdrawn, change the circle color from light grey to something else [from Victor]

**Comment by davidblader** [comment]
7- update vimeo video hack fix before anyone notices

**Comment by mohadesz** [comment]
8- Notification (Instead of daily notification, a Study tracker Digest can be emailed weekly to specific set of users
