### ISSUE TITLE
Study Tracker Improvements Phase 4.0 

### ISSUE THREAD

**Issue by mohadesz** [taracampbell/Loris#45]
- [ ] - Include the Monitoring Flag - David
    - Front-end feature 
    - Back-end

- [ ] - Add URL routing within the Dashboard so the back button works, etc. - Tara

- [ ] - Notification (Instead of daily notification, a Study tracker Digest can be emailed weekly to specific set of users
         - A printed view/snapshot of the list?  

- [x] Extra filter options for participant_status 

- [x]  Loading screen Ajax Feature 

- [x] include #'s for instruments where Administration is set to All, Partial, or None

- [ ] 'Data not yet sent to DCC' Only shows up for some of the visits. Check Candidate CBH1151
- [ ] update vimeo video hack fix before anyone notices  
- [ ] Study tracker specific permission (i.e. only coordinators should be able to see study tracker as per Jennifer/Victor's request
