### ISSUE TITLE
Study Tracker Improvements Phase 3.1

### ISSUE THREAD

**Issue by mohadesz** [taracampbell/Loris#50]
- [x] CCNA Override - Tara
- [x] Feedbacks provided from the demo of Phase 3.0 - David
- [x] Message if nothing is displayed  - David
- [x] N/A displayed for those visits not corresponding to the filtered Cohort (i.e. FTD)-  David
- [x] Having the feedback, conflicts and the Data monitoring flag displayed next to the visit?? - David
- [x] Adding the Legend

**Comment by mohadesz** [comment]
@davidblader @taracampbell Make sure that the tasks on https://github.com/taracampbell/Loris/issues/22 are completed.

**Comment by mohadesz** [comment]
@taracampbell let's talk about 'Study tracker specific permission'
